remote_theme: pages-themes/midnight@v0.2.0
layout: splash
classes:
  - landing
  - dark-theme
lsi: false
safe: true
incremental: false
# highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
#   syntax_highlighter: rouge
